name = "maria-fatima"
compatibility_date = "2025-08-01"
pages_build_output_dir = "./dist"

[assets]
directory = "./dist"

# Cloudflare Configuration
# Build command: npm run build
# Build output: dist
